server:
  port: ${PORT:8085}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5437/payments}
    username: ${DATABASE_USER:commerce}
    password: ${DATABASE_PASSWORD:commerce}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:19092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  swagger-ui:
    path: /docs
